modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="vincentmet" #optional
[[mods]] #mandatory
modId="smm" #mandatory
version="1.14.4-1.0.0" #mandatory
displayName="Scrollable Main Menu" #mandatory
description='''
Wooooooooosssshhh!!!
'''